github actions smoke build (#227)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,8 @@
 name: Release Charts
 
+permissions:
+  contents: read
+
 on:
   push:
     branches:
@@ -10,6 +13,8 @@ on:
 jobs:
   release:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
 
     steps:
       - name: Checkout
@@ -38,6 +43,19 @@ jobs:
         uses: helm/chart-releaser-action@v1.7.0
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: Extract Chart Version from Chart.yaml
+        id: extract_version
+        run: |
+          CHART_VERSION=$(grep '^version:' charts/mlrun-ce/Chart.yaml | awk '{print $2}')
+          if [[ -z "$CHART_VERSION" ]]; then
+            echo "Error: Failed to extract version from Chart.yaml" >&2
+            exit 1
+          fi
+          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT
+
+    outputs:
+      version: ${{ steps.extract_version.outputs.version }}
 
   notify_mlefi:
     runs-on: ubuntu-latest
@@ -74,3 +92,14 @@ jobs:
             -H "Authorization: token ${{ secrets.MLEFIGHTRIGGER }}" \
             https://api.github.com/repos/iguazio/mlefi/dispatches \
             -d "$JSON_PAYLOAD"
+
+  deploy_ce_onprem:
+    needs: release
+    uses: ./.github/workflows/deploy_ce_onprem_public.yaml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      GH_APP_ID: ${{ secrets.GH_APP_ID }}
+      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
+      DEPLOYMENT_REPO: ${{ secrets.DEPLOYMENT_REPO }}
+      SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
